export const AJAX_BEGIN = 'AJAX_BEGIN';
export const AJAX_END = 'AJAX_END';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_MOTORS_SUCCESS = 'FETCH_MOTORS_SUCCESS';
export const FETCH_MOTO_DETAILS_SUCCESS = 'FETCH_MOTO_DETAILS_SUCCESS';
export const FETCH_VIDEO_DETAILS_SUCCESS = 'FETCH_MOTO_DETAILS_SUCCESS';
export const CREATE_VIDEO_SUCCESS = 'CREATE_VIDEO_SUCCESS';
export const CREATE_MOTOR_SUCCESS = 'CREATE_MOTOR_SUCCESS';
export const DELETE_MOTOR_SUCCESS = 'DELETE_MOTOR_SUCCESS';
export const DELETE_VIDEO_SUCCESS = 'DELETE_VIDEO_SUCCESS';
export const EDIT_MOTOR_SUCCESS = 'EDIT_MOTOR_SUCCESS'
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_DETAILS_SUCCESS = 'FETCH_CONTACTS_DETAILS_SUCCESS';
export const CREATE_CONTACTS_SUCCESS = 'CREATE_CONTACTS_SUCCESS';
export const DELETE_CONTACTS_SUCCESS = 'DELETE_CONTACTS_SUCCESS';
export const FETCH_USER_CONTACTS_SUCCESS = 'FETCH_USER_CONTACTS_SUCCESS';
export const FETCH_USER_CONTACTS_DETAILS_SUCCESS = 'FETCH_USER_CONTACTS_DETAILS_SUCCESS';
export const EDIT_USER_CONTACTS_SUCCESS = 'EDIT_USER_CONTACTS_SUCCESS';
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const C_H_SUCCESS = 'C_H_SUCCESS';

export const FETCH_HOTELS_SUCCESS = 'FETCH_HOTELS_SUCCESS';
export const DELETE_HOTEL_SUCCESS = 'DELETE_HOTEL_SUCCESS';
export const EDIT_HOTEL_SUCCESS = 'EDIT_HOTEL_SUCCESS';







